################################################################################
# Copyright (c) IBM Corporation 2024
################################################################################
# This file is required when using repository directly in AWX/Tower
# for more info: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file
#                https://docs.ansible.com/ansible-tower/latest/html/userguide/projects.html#collections-support
---
collections:
  - name: ibm.ibm_zos_core
    version: 1.8.0
  - name: ibm.ibm_zos_cics
    version: 2.1.0
